from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass, field
from typing import Mapping
from uuid import uuid4

from spice.llm.core.provider import LLMProvider, LLMResponseError
from spice.llm.core.task_hooks import LLMTaskHook
from spice.llm.core.types import LLMModelConfig, LLMRequest, LLMResponse


@dataclass(slots=True)
class DeterministicLLMProvider(LLMProvider):
    provider_id: str = "deterministic"
    responses: Mapping[LLMTaskHook, str] = field(default_factory=dict)

    def generate(self, request: LLMRequest, model: LLMModelConfig) -> LLMResponse:
        start = time.perf_counter()
        output_text = self.responses.get(request.task_hook)
        if output_text is None:
            output_text = _default_output_for_hook(request)

        latency_ms = int((time.perf_counter() - start) * 1000)
        return LLMResponse(
            provider_id=self.provider_id,
            model_id=model.model_id,
            output_text=output_text,
            raw_payload={
                "provider_id": self.provider_id,
                "task_hook": request.task_hook.value,
            },
            finish_reason="stop",
            usage={
                "input_chars": len(request.input_text),
                "output_chars": len(output_text),
            },
            latency_ms=latency_ms,
            request_id=f"det-{uuid4().hex}",
        )


def _default_output_for_hook(request: LLMRequest) -> str:
    hook = request.task_hook
    if hook == LLMTaskHook.ASSIST_DRAFT:
        domain_hint = request.domain or str(request.metadata.get("domain_name", "assist_domain"))
        domain_id = _normalize_domain_id(domain_hint)
        action_id = f"{domain_id}.monitor"
        observation_type = f"{domain_id}.signal"
        outcome_type = f"{domain_id}.transition"
        draft_spec = {
            "schema_version": "spice.domain_spec.v1",
            "domain": {"id": domain_id},
            "vocabulary": {
                "observation_types": [observation_type],
                "action_types": [action_id],
                "outcome_types": [outcome_type],
            },
            "state": {
                "entity_id": f"{domain_id}.current",
                "fields": [{"name": "status", "type": "string", "default": "open"}],
            },
            "actions": [
                {
                    "id": action_id,
                    "executor": {"type": "mock", "operation": action_id, "parameters": {}},
                    "expected_outcome_type": outcome_type,
                }
            ],
            "decision": {"default_action": action_id},
            "demo": {
                "observations": [
                    {
                        "type": observation_type,
                        "source": f"{domain_id}.assist",
                        "attributes": {"status": "open"},
                    }
                ]
            },
        }
        payload = {
            "draft_spec": draft_spec,
            "assumptions": ["Generated by deterministic provider."],
            "warnings": [],
            "missing_info": [],
            "confidence": {"overall": 0.2, "source": "deterministic_provider"},
        }
        return json.dumps(payload, ensure_ascii=True)

    if hook == LLMTaskHook.PERCEPTION_INTERPRET:
        payload = {
            "id": f"obs-{uuid4().hex}",
            "observation_type": "generic",
            "source": "deterministic.provider",
            "attributes": {},
            "metadata": {"provider": "deterministic"},
        }
        return json.dumps(payload, ensure_ascii=True)

    if hook == LLMTaskHook.DECISION_PROPOSE:
        payload = [
            {
                "id": f"dec-{uuid4().hex}",
                "decision_type": "generic",
                "status": "proposed",
                "selected_action": "noop_software_action",
                "refs": [],
                "metadata": {"provider": "deterministic"},
                "attributes": {},
            }
        ]
        return json.dumps(payload, ensure_ascii=True)

    if hook == LLMTaskHook.RESPONSE_COMPOSE:
        payload = {
            "response": "Decision brief\nI'd choose the selected option.\n\nThis deterministic provider does not rewrite response text."
        }
        return json.dumps(payload, ensure_ascii=True)

    if hook == LLMTaskHook.SIMULATION_ADVISE:
        payload = {"score": 0.0, "summary": "deterministic simulation artifact"}
        return json.dumps(payload, ensure_ascii=True)

    if hook == LLMTaskHook.REFLECTION_SYNTHESIZE:
        payload = {
            "id": f"ref-{uuid4().hex}",
            "reflection_type": "generic",
            "status": "recorded",
            "refs": [],
            "insights": {"summary": "deterministic reflection"},
            "attributes": {"provider": "deterministic"},
        }
        return json.dumps(payload, ensure_ascii=True)

    raise LLMResponseError(f"Unsupported deterministic hook: {hook!r}")


def _normalize_domain_id(value: str) -> str:
    token = re.sub(r"[^a-z0-9]+", "_", value.strip().lower())
    token = token.strip("_")
    if not token:
        token = "assist_domain"
    if token[0].isdigit():
        token = f"domain_{token}"
    return token
